"use client";
import {useMemo,useState} from "react";
type Product={id:number;name:string;category:string;price:number;oldPrice?:number;rating:number;reviews:number;badge?:string;emoji:string;color:string;specs:string};
const products:Product[]=[
{id:1,name:"NovaBook Air 14",category:"Laptops",price:899.99,oldPrice:1099.99,rating:4.8,reviews:214,badge:"Best seller",emoji:"▱",color:"#bed7ea",specs:"M3 • 16GB • 512GB"},{id:2,name:"Aether RTX 4070",category:"Components",price:579.99,oldPrice:649.99,rating:4.7,reviews:168,badge:"Save $70",emoji:"▥",color:"#c7c9ed",specs:"12GB GDDR6X"},{id:3,name:"Pulse Pro Wireless",category:"Gaming",price:89.99,rating:4.9,reviews:342,badge:"Top rated",emoji:"⌁",color:"#f5c7b8",specs:"26K DPI • 70 hr"},{id:4,name:"ArcView 27” 4K",category:"Monitors",price:349.99,oldPrice:429.99,rating:4.6,reviews:127,badge:"Limited deal",emoji:"▰",color:"#bde4d1",specs:"144Hz • HDR600"},{id:5,name:"Echo Keys 75",category:"Accessories",price:119.99,rating:4.8,reviews:96,emoji:"⌨",color:"#ead5a9",specs:"Hot-swap • RGB"},{id:6,name:"ByteCore Mini PC",category:"Desktops",price:699.99,rating:4.7,reviews:81,badge:"New",emoji:"▦",color:"#d3c5e8",specs:"Ryzen 7 • 32GB"},{id:7,name:"Orbit USB-C Hub",category:"Accessories",price:54.99,rating:4.5,reviews:203,emoji:"⌘",color:"#b9dbe0",specs:"9-in-1 • 100W PD"},{id:8,name:"Sonic Cloud Headset",category:"Gaming",price:139.99,oldPrice:169.99,rating:4.8,reviews:188,badge:"Save $30",emoji:"◉",color:"#edc5ce",specs:"Spatial audio • ANC"}];
const categories=["All","Laptops","Components","Gaming","Monitors","Accessories","Desktops"];
export default function Home(){const[category,setCategory]=useState("All"),[query,setQuery]=useState(""),[cart,setCart]=useState<Record<number,number>>({}),[cartOpen,setCartOpen]=useState(false),[toast,setToast]=useState("");const shown=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);const count=Object.values(cart).reduce((a,b)=>a+b,0),subtotal=products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0);function add(p:Product){setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}));setToast(`${p.name} added to cart`);setTimeout(()=>setToast(""),2200)}function qty(id:number,n:number){setCart(c=>{const x={...c};if(n<=0)delete x[id];else x[id]=n;return x})}return <main>
<header className="topbar"><div className="nav wrap"><a className="brand" href="#top"><span className="brandmark">B</span><span>BYTE <b>BAZAAR</b></span></a><div className="search"><span>⌕</span><input aria-label="Search products" placeholder="Search 50,000+ tech products" value={query} onChange={e=>setQuery(e.target.value)}/><button>Search</button></div><nav><a href="#shop">Shop</a><a href="#deals">Deals</a><a href="#support">Support</a></nav><button className="cartButton" onClick={()=>setCartOpen(true)}>Bag <span>{count}</span></button></div></header>
<section id="top" className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">THE NEXT WAVE OF TECH</div><h1>Upgrade your<br/><em>digital world.</em></h1><p>Powerful gear. Honest prices. Expert support. Everything you need to build, play, and create—shipped fast.</p><div className="heroActions"><a className="primary" href="#shop">Shop new arrivals →</a><a className="secondary" href="#deals">Explore deals</a></div><div className="trust"><span>✓ Free 2-day shipping</span><span>✓ 30-day returns</span><span>✓ Expert support</span></div></div><div className="heroArt"><div className="orb one"/><div className="orb two"/><div className="device"><div className="screen"><span>BYTE</span><strong>Power up.</strong><i/></div><div className="base"/></div><div className="floatCard fc1"><small>PERFORMANCE</small><b>Built for speed</b></div><div className="floatCard fc2"><span>★★★★★</span><b>4.9 customer rating</b></div></div></div></section>
<section className="perks"><div className="wrap perkGrid"><div><b>⚡</b><span><strong>Fast & free shipping</strong><small>On orders over $49</small></span></div><div><b>↻</b><span><strong>Easy returns</strong><small>30-day peace of mind</small></span></div><div><b>♢</b><span><strong>Price match</strong><small>Get the best price</small></span></div><div><b>☏</b><span><strong>Real tech support</strong><small>Here when you need us</small></span></div></div></section>
<section id="shop" className="catalog wrap"><div className="sectionHead"><div><span className="eyebrow dark">CURATED FOR YOU</span><h2>Featured tech</h2></div><a href="#shop">View all products →</a></div><div className="filters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="productGrid">{shown.map(p=><article className="product" key={p.id}><div className="productVisual" style={{background:p.color}}>{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart">♡</button><div className="productIcon">{p.emoji}</div></div><div className="productInfo"><small>{p.category}</small><h3>{p.name}</h3><p>{p.specs}</p><div className="rating"><span>★★★★★</span> {p.rating} ({p.reviews})</div><div className="buy"><div><strong>${p.price.toFixed(2)}</strong>{p.oldPrice&&<del>${p.oldPrice.toFixed(2)}</del>}</div><button onClick={()=>add(p)}>+</button></div></div></article>)}</div>{!shown.length&&<div className="empty">No products match “{query}”. Try another search.</div>}</section>
<section id="deals" className="deal"><div className="wrap dealInner"><div><span className="eyebrow">WEEKEND DROP</span><h2>Save up to 30%<br/>on gaming gear.</h2><p>Level up your setup with hand-picked deals. While supplies last.</p><a className="primary light" href="#shop" onClick={()=>setCategory("Gaming")}>Shop gaming deals →</a></div><div className="dealGraphic"><span>30<sup>%</sup><small>OFF</small></span></div></div></section>
<section id="support" className="newsletter wrap"><div><span className="eyebrow dark">STAY IN THE LOOP</span><h2>Fresh tech, straight to your inbox.</h2><p>Get first access to new drops, deals, and expert tips.</p></div><form onSubmit={e=>{e.preventDefault();setToast("You're on the list!")}}><input required type="email" placeholder="you@example.com"/><button>Sign me up →</button></form></section>
<footer><div className="wrap foot"><div className="brand"><span className="brandmark">B</span><span>BYTE <b>BAZAAR</b></span></div><p>Tech for the way you live, work, and play.</p><div><a href="#shop">Products</a><a href="#support">Help center</a><a href="#top">About</a></div><small>© 2026 Byte Bazaar. Built for curious minds.</small></div></footer>{toast&&<div className="toast">✓ {toast}</div>}
{cartOpen&&<div className="overlay" onMouseDown={()=>setCartOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawerHead"><h2>Your cart <span>{count}</span></h2><button onClick={()=>setCartOpen(false)}>×</button></div>{!count?<div className="cartEmpty"><b>◇</b><h3>Your cart is ready for something great.</h3><button className="primary" onClick={()=>setCartOpen(false)}>Start shopping</button></div>:<><div className="cartItems">{products.filter(p=>cart[p.id]).map(p=><div className="cartItem" key={p.id}><div style={{background:p.color}}>{p.emoji}</div><section><b>{p.name}</b><small>{p.specs}</small><strong>${p.price.toFixed(2)}</strong><nav><button onClick={()=>qty(p.id,cart[p.id]-1)}>−</button><span>{cart[p.id]}</span><button onClick={()=>qty(p.id,cart[p.id]+1)}>+</button></nav></section></div>)}</div><div className="cartTotal"><p><span>Subtotal</span><b>${subtotal.toFixed(2)}</b></p><small>Shipping and taxes calculated at checkout.</small><button onClick={()=>setToast("Demo checkout ready — connect payments to launch.")}>Checkout securely →</button></div></>}</aside></div>}</main>}
